server:
  port: 8081
  undertow:
    threads:
      io: 16
      worker: 256
  shutdown: graceful
spring:
  application.name: redistest
  data:
    redis:
      port: 6379
      lettuce.pool:
         max-active: 8 # Số kết nối tối đa, giá trị âm là no limit
        # min-idle: 0 # kết nối nhàn rỗi tối thiểu
        # max-idle: 8 # kết nối nhàn rỗi tối đa
        # max-wait: -1ms # thời gian đợi kết nối khi pool cạn kiệt trước khi throw exception, giá trị âm sẽ đợi vô hạn
        # time-between-eviction-runs: 1000 # sau bao lâu sẽ chạy evict idle connect

  #      database: 10 # 16 cơ sở dữ liệu (được đánh số từ 0 đến 15) trong một instance Redis để tách logic
  datasource:
    url: jdbc:h2:file:./data/h2
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      pool-name: redis-test-pool
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 600000
      connection-timeout: 10000
      leak-detection-threshold: 2000
      validation-timeout: 250
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      '[hibernate.generate_statistics]': false
  cache:
    redis:
      cache-null-values: false
      enable-statistics: true
      time-to-live: 100000
      use-key-prefix: true
#      key-prefix: ${spring.application.name}_${}
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
logbook:
  obfuscate:
    headers:
      - Authorization
  include:
    - /**
  exclude:
    - /health
    - /actuator/**
    - /swagger-ui**
    - /api-docs/**